language: scala
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-$CI_VERSION.tar.gz | tar xz
- cp .ci/sbt-ci-build-doc-simple.sh ci/
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
- cp /etc/sbt/sbtopts .sbtopts; echo "-Dsbt.global.base=$TRAVIS_BUILD_DIR/ci" >> .sbtopts
script:
- sbt test package scripted
  && ci/sbt-ci-deploy.sh ivy http://commbank.artifactoryonline.com/commbank ext-releases-local-ivy
  && ci/sbt-ci-build-doc-simple.sh
  && if git rev-parse --verify refs/heads/gh-pages 2>&/dev/null; then ci/ci-push-branch.sh gh-pages; fi
after_script:
- rm -rf ci
- find $HOME/.ivy2 -name "*uniform*" -delete
env:
  global:
  - CI_VERSION=3.3.1-20161112085142-c2c258a
  - secure: gRyNyPY1Z/nk1rvf5gP3QCG0D0/u9rChVn4n9/gBUSCVM1CD7PD3JPq8mPDoBp8s6A7d92ubKjCYB+4ZtJr9xiGEajTWb4cF9u4U2HPN1uRdNQcH3UypKG++rk4eWifqQ0rYs84GtmRrvB/JD75dpjqulFxqXwBzwZPJT95Ky5I=
  - secure: Gl5MkAv89lDsBAYUJcXfAEpjqjVSicj+Ux6nx/UnXbzkniPosZ+6isuMbF1wBZebgspTWmrqegt4ivuCY15HSqOx9/4JwHsZuqEI73RkgMmo75Oo7uRFAXGT5tqMxUvhijcCwSGc1zGlXV6o2Uz6FIuboIGXMOhhlWsPpfSvZvo=
before_install:
- openssl aes-256-cbc -K $encrypted_3dcda697bb71_key -iv $encrypted_3dcda697bb71_iv
  -in .ci/deploy-key.enc -out .ci/deploy-key.pem -d
